version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "articles:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on: 
      - zookeeper

  spark-master:
    image: bde2020/spark-master:3.1.1-hadoop3.2
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
  
  spark-worker:
    image: bde2020/spark-worker:3.1.1-hadoop3.2
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
  db:
    image: mysql:8.0.19
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql 
  producer:
    build: .
    environment: 
      BROKER: kafka:9092
    command: sh -c "spark-submit --master spark://spark-master:7077 static_producer.py"
    depends_on: 
      - spark-master
      - kafka
      
  consumer:
    build: .
    environment: 
      BROKER: kafka:9092
    command: "spark-submit --master spark://spark-master:7077 static_consumer.py"
    depends_on:
      - spark-master
      - kafka
      - producer
      - db
volumes:
  db-data:
secrets:
  db-password:
    file: password.txt
